name: Run tests and publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Run Cucumber tests
      run: |
        gem install cucumber codecov
        export PATH=$PATH:$PWD
        cucumber

  publish:
    name: Build + Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        version: 2.4

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
